### ISSUE TITLE
luci-app-unblockneteasemusic 日志出错，软件界面提示无法联网

### ISSUE THREAD

**Issue by zhengjun131461** [kenzok8/small-package#170]
固件自己编译，luci-app-unblockneteasemusic版本2.14.3
日志：
Succeeded in updating core.
Current core version: a918455aed15a389e2358b1c28b6536f5606b1fe.

INFO: (app) HTTP Server running @ http://0.0.0.0:5200
INFO: (app) HTTPS Server running @ http://0.0.0.0:5201
ERROR: (hook) A error occurred in hook.request.after when hooking https://interface.music.163.com/eapi/v1/discovery/recommend/songs.
    Error: Trying to add data in unsupported state
        at Decipheriv.update (node:internal/crypto/cipher:181:29)
        at c (/usr/share/unblockneteasemusic/core/app.js:3:852)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:3:1023)
        at /usr/share/unblockneteasemusic/core/app.js:3:10676
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERROR: (hook) A error occurred in hook.request.after when hooking https://interface.music.163.com/eapi/batch.
    Error: Trying to add data in unsupported state
        at Decipheriv.update (node:internal/crypto/cipher:181:29)
        at c (/usr/share/unblockneteasemusic/core/app.js:3:852)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:3:1023)
        at /usr/share/unblockneteasemusic/core/app.js:3:10676
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERROR: (hook) A error occurred in hook.request.after when hooking https://interface.music.163.com/eapi/v1/discovery/recommend/songs.
    Error: Trying to add data in unsupported state
        at Decipheriv.update (node:internal/crypto/cipher:181:29)
        at c (/usr/share/unblockneteasemusic/core/app.js:3:852)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:3:1023)
        at /usr/share/unblockneteasemusic/core/app.js:3:10676
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERROR: (hook) A error occurred in hook.request.after when hooking https://interface.music.163.com/eapi/batch.
    Error: Trying to add data in unsupported state
        at Decipheriv.update (node:internal/crypto/cipher:181:29)
        at c (/usr/share/unblockneteasemusic/core/app.js:3:852)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:3:1023)
        at /usr/share/unblockneteasemusic/core/app.js:3:10676
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERROR: (hook) A error occurred in hook.request.after when hooking https://interface.music.163.com/eapi/v1/discovery/recommend/songs.
    Error: Trying to add data in unsupported state
        at Decipheriv.update (node:internal/crypto/cipher:181:29)
        at c (/usr/share/unblockneteasemusic/core/app.js:3:852)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:3:1023)
        at /usr/share/unblockneteasemusic/core/app.js:3:10676
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERROR: (hook) A error occurred in hook.request.after when hooking https://interface.music.163.com/eapi/v6/playlist/detail.
    Error: Trying to add data in unsupported state
        at Decipheriv.update (node:internal/crypto/cipher:181:29)
        at c (/usr/share/unblockneteasemusic/core/app.js:3:852)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:3:1023)
        at /usr/share/unblockneteasemusic/core/app.js:3:10676
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERROR: (hook) A error occurred in hook.request.after when hooking https://interface.music.163.com/eapi/v3/song/detail.
    Error: Trying to add data in unsupported state
        at Decipheriv.update (node:internal/crypto/cipher:181:29)
        at c (/usr/share/unblockneteasemusic/core/app.js:3:852)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:3:1023)
        at /usr/share/unblockneteasemusic/core/app.js:3:10676
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
INFO: (provider/match) Replaced: [363015] 我一定要得到你
    audioId: 363015
    songName: "我一定要得到你"
    url: "http://nf.sycdn.kuwo.cn/f913a7d4232d5ff1437cc92af4d6c160/666704d8/resource/n3/58/79/2272659253.mp3?bitrate"
ERROR: (hook) A error occurred in hook.request.after when hooking https://interface.music.163.com/eapi/batch.
    Error: Trying to add data in unsupported state
        at Decipheriv.update (node:internal/crypto/cipher:181:29)
        at c (/usr/share/unblockneteasemusic/core/app.js:3:852)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:3:1023)
        at /usr/share/unblockneteasemusic/core/app.js:3:10676
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERROR: (hook) A error occurred in hook.request.after when hooking https://interface.music.163.com/eapi/v1/discovery/recommend/songs.
    Error: Trying to add data in unsupported state
        at Decipheriv.update (node:internal/crypto/cipher:181:29)
        at c (/usr/share/unblockneteasemusic/core/app.js:3:852)
        at Object.decrypt (/usr/share/unblockneteasemusic/core/app.js:3:1023)
        at /usr/share/unblockneteasemusic/core/app.js:3:10676
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

网易云软件版本：3.00,202739，

**Comment by kenzok8** [comment]
自动巡检：该 Issue 长时间未更新（>=180 天）且无后续反馈，先关闭以便集中处理当前问题。

如问题仍存在，请按最新源码重新复现后提交新 Issue，并附：
- 固件版本与目标架构
- 完整编译/运行日志（从第一个报错开始）
- 复现步骤

Auto triage: this issue has been inactive for >=180 days with no follow-up, so it is being closed for backlog cleanup.
If the issue still exists, please open a new issue with updated logs and reproduction steps.

**Comment by kenzok8** [comment]
Closed by automated stale triage.
